package com.twitterdan.dto;

public enum DtoResponseType {
  MESSAGE_ADD,
  MESSAGE_DELETE,
  MESSAGE_OWNER_SEEN,
  FOREIGNER_MESSAGE_SEEN,
  PRIVATE_CHAT,
  GROUP_CHAT,
  UPDATE_GROUP_CHAT,
  LEAVE_CHAT,
}
